### ISSUE TITLE
3.0.1: ActiveRecord::StaleObjectError

### ISSUE THREAD

**Issue by marutosi** [collectiveidea/awesome_nested_set#280]
3.0.1 breaks Redmine Rails4 porting test.

https://github.com/marutosi/redmine-bb/tree/bb-svn-rails4.1
https://github.com/marutosi/redmine-bb/commit/54b2d413330ee0b41cb128b1ff25965cee8bd74c

<pre>
  1) Error:
IssueTest#test_destroying_a_deleted_issue_should_not_raise_an_error:
ActiveRecord::StaleObjectError: Attempted to destroy a stale object: Issue
    app/models/issue.rb:188:in `destroy'
    test/unit/issue_test.rb:1419:in `block (2 levels) in test_destroying_a_deleted_issue_should_not_raise_an_error'
    test/unit/issue_test.rb:1418:in `block in test_destroying_a_deleted_issue_should_not_raise_an_error'
    test/unit/issue_test.rb:1417:in `test_destroying_a_deleted_issue_should_not_raise_an_error'
</pre>

3.0.0 passes this test.

**Comment by marutosi** [comment]
Following change fixes on Redmine trunk revision 13839.
http://www.redmine.org/projects/redmine/repository/revisions/13839

<pre>
=== (+2,-2) app/models/issue.rb ===
@@ -185,7 +185,7 @@
   # the lock_version condition should not be an issue but we handle it.
   def destroy
     super
-  rescue ActiveRecord::RecordNotFound
+  rescue ActiveRecord::StaleObjectError, ActiveRecord::RecordNotFound
     # Stale or already deleted
     begin
       reload
</pre>
