### ISSUE TITLE
NoMethodError: undefined method `join_sql'

### ISSUE THREAD

**Issue by frankie-loves-jesus** [collectiveidea/awesome_nested_set#293]
Hi! Just upgraded my awesome_nested_set but am now seeing this whenever I'm trying to load my seeds:

```
% bundle exec rake db:seed RAILS_ENV=production --trace
NoMethodError: undefined method `join_sql' for #<Arel::SelectManager:0x007fc6bfdf03f8>
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/set_validator.rb:32:in `join_scope'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/set_validator.rb:26:in `query'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/set_validator.rb:13:in `valid?'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/model/validatable.rb:14:in `left_and_rights_valid?'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/model/validatable.rb:10:in `valid?'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/tree.rb:20:in `rebuild!'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/model/rebuildable.rb:15:in `block in rebuild!'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/scoping/default.rb:33:in `block in unscoped'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:302:in `scoping'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/scoping/default.rb:33:in `unscoped'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/awesome_nested_set-3.0.1/lib/awesome_nested_set/model/rebuildable.rb:14:in `rebuild!'
/home/www/myapp/db/seeds/categories.rb:32:in `<top (required)>'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/www/myapp/db/seeds.rb:2:in `block in <top (required)>'
/home/www/myapp/db/seeds.rb:2:in `each'
/home/www/myapp/db/seeds.rb:2:in `<top (required)>'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:547:in `load_seed'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:139:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/www/myapp/bin/rake:8:in `<top (required)>'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/www/myapp/vendor/cache/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
Tasks: TOP => db:setup => db:seed
```

Anybody else getting this too?

**Comment by parndt** [comment]
What'd you upgrade from? Did you upgrade anything else at the same time?

**Comment by frankie-loves-jesus** [comment]
Hello @parndt!

Turns out I shouldn't have changed `gem "awesome_nested_set", github: "collectiveidea/awesome_nested_set"` to `gem "awesome_nested_set"`.

I thought I was being smart ;)

**Comment by frankie-loves-jesus** [comment]
@parndt any idea why `gem "awesome_nested_set"` doesn't work though?

**Comment by parndt** [comment]
To install the latest version you can specify this in your Gemfile:

```ruby
gem "awesome_nested_set", "~> 3.0.1"
```

Then, run:

```
bundle update awesome_nested_set
```

**Comment by frankie-loves-jesus** [comment]
Thanks, will do. I just find it odd though that `gem "awesome_nested_set"` alone doesn't work.

**Comment by parndt** [comment]
@frankie-loves-jesus well we pushed a new gem release today, version 3.0.2, which doesn't have the bug that you were mentioning so perhaps that's it?
